server {
    listen ${PORT};
    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "frame-ancestors *" always;
    add_header Access-Control-Allow-Origin "*" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
        add_header Content-Security-Policy "frame-ancestors *" always;
        add_header Access-Control-Allow-Origin "*" always;
    }
}
